Add ValueConvertible conformance to Swift Bool
Zewo/SQL pull request #20
Opened 2016-11-17 17:51 UTC by rcedwards

Addresses https://github.com/Zewo/Zewo/issues/222

2016-11-18 01:44 UTC, Danappelxx requested changes
Great thanks for the pr! Just a few minor things.

2016-11-18 01:44 UTC, Danappelxx commented on Sources/SQL/Core/Value.swift
> +        let stringValue = try String(buffer: buffer)
Could you use `Int(buffer:)` here?

2016-11-18 01:44 UTC, Danappelxx commented on Sources/SQL/Core/Value.swift
> +        guard stringValue == "1" || stringValue == "0" else {
I would use a switch:
```swift
switch value {
    case 0: return false
    case 1: return true
    default: throw ValueError(...)
}
```

2016-11-18 01:44 UTC, Danappelxx commented on Sources/SQL/Core/Value.swift
> +        return .string(String(self ? "1" : "0"))
Use Int's implementation here: `(self ? 1 : 0).sqlValue`

2016-11-18 01:44 UTC, Danappelxx commented on Tests/SQLTests/SQLTests.swift
> +    let admin: Bool
`isAdmin`, maybe? Not important.

2016-11-18 14:07 UTC, rcedwards commented
Sounds good. I'll address those now.

2016-11-19 19:46 UTC, Danappelxx approved these changes

2016-11-19 19:46 UTC, Danappelxx commented
Awesome! Waiting for travis to pass and I'll merge!

2016-11-19 19:57 UTC, merged

2016-12-07 20:42 UTC, rcedwards commented
@Danappelxx I've discovered today that this implementation will not work with a postgres boolean field, since the buffer is returned as either "t" or "f".

Would you entertain an implementation similar to this:
```
extension Bool: ValueConvertible {
    public init(rawSQLData buffer: Buffer) throws {
        // read int, 0 = false, 1 = true
        let value = try Int(rawSQLData: Bool.sanitizedBooleanBuffer(rawBuffer: buffer))

        switch value {
        case 0: self = false
        case 1: self = true
        default: throw ValueError(description: "Failed to convert data to Bool. Excepted 0/1, got \(value).")
        }
    }

    public var sqlValue: Value {
        return (self ? 1 : 0).sqlValue
    }

    private static func sanitizedBooleanBuffer(rawBuffer: Buffer) -> Buffer {
        guard let bufferPrefix = rawBuffer.first else {
            return rawBuffer
        }
        let hex0: UInt8 = 0x30
        let hex1: UInt8 = 0x31
        let hexLowercaseT: UInt8 = 0x74
        let hexLowercaseF: UInt8 = 0x66

        switch bufferPrefix {
        case hexLowercaseT:
            return Buffer("1")
        case hexLowercaseF:
            return Buffer("0")
        case hex0, hex1:
            break
        default:
            break
        }
        return rawBuffer
    }
}
```

This works well but I could see the concern of being to database specific within the SQL framework. That being said it would be tricky to "override" this in the postgres framework since this is just an extension on bool that would collide if we tried to implement it over in https://github.com/Zewo/PostgreSQL.

Thoughts?